### PR TITLE
Fix #769: Wrong NodeIDs offset for BinaryEncoding

### LINKED ISSUE #769: Wrong NodeIDs offset for BinaryEncoding
In commit https://github.com/open62541/open62541/commit/952072a3469f12dbb2c406d9dbd8689182fbc2b1 @jpfr  updated the `NodeIds.csv` to the most recent version.

Most of the (old) node IDs look something like this:
```
 FindServersRequest,420,DataType
 FindServersRequest_Encoding_DefaultXml,421,Object
 FindServersRequest_Encoding_DefaultBinary,422,Object
```
So encoding binary is just the main ID+2.
That's also used when constructing the binary message:
https://github.com/open62541/open62541/blob/0.2/include/ua_constants.h#L104
and
https://github.com/open62541/open62541/blob/0.2/src/ua_securechannel.c#L222

Unfortunately this does not work anymore for new types. If you check the new NodeIds.csv, there is for example:
```
ServerOnNetwork,12189,DataType
FindServersOnNetworkRequest,12190,DataType
FindServersOnNetworkResponse,12191,DataType
RegisterServer2Request,12193,DataType
RegisterServer2Response,12194,DataType
ServerOnNetwork_Encoding_DefaultXml,12195,Object
FindServersOnNetworkRequest_Encoding_DefaultXml,12196,Object
FindServersOnNetworkResponse_Encoding_DefaultXml,12197,Object
RegisterServer2Request_Encoding_DefaultXml,12199,Object
RegisterServer2Response_Encoding_DefaultXml,12200,Object
OpcUa_XmlSchema_ServerOnNetwork,12201,Variable
OpcUa_XmlSchema_ServerOnNetwork_DataTypeVersion,12202,Variable
OpcUa_XmlSchema_ServerOnNetwork_DictionaryFragment,12203,Variable
ServerOnNetwork_Encoding_DefaultBinary,12207,Object
FindServersOnNetworkRequest_Encoding_DefaultBinary,12208,Object
FindServersOnNetworkResponse_Encoding_DefaultBinary,12209,Object
RegisterServer2Request_Encoding_DefaultBinary,12211,Object
RegisterServer2Response_Encoding_DefaultBinary,12212,Object
```

Especially look at (https://github.com/open62541/open62541/blob/0.2/tools/schema/NodeIds.csv#L4822)
```
RegisterServer2Request,12193,DataType
RegisterServer2Response,12194,DataType
ServerOnNetwork_Encoding_DefaultXml,12195,Object
```
The node ID 12195 is NOT `RegisterServer2Request_Encoding_DefaultBinary` but `ServerOnNetwork_Encoding_DefaultXml`

So just offsetting the NodeID by 2 to get the ID for Binary Encoding does not work anymore, and wrong node IDs are sent.

Do you have any idea/suggestion how to fix this?

### PR DESCRIPTION
**Pull request by Pro**
See #769 for additional description of the problem.

This is my proposed solution for the problem.
Each DataType struct stores the correct NodeID for binary/XML encoded.

Open for feedback or direct merge

### CODE REVIEW

File: src/ua_types_encoding_binary.c [hunk 1]
```diff
@@ -778,8 +786,15 @@ ExtensionObject_decodeBinary(UA_ExtensionObject *dst, const UA_DataType *_) {
         /* helping clang analyzer, typeId is numeric */
         UA_assert(typeId.identifier.byteString.data == NULL);
         UA_assert(typeId.identifier.string.data == NULL);
-        typeId.identifier.numeric -= UA_ENCODINGOFFSET_BINARY;
-        findDataType(&typeId, &type);
+        size_t i;
+        for (i = 0; i<UA_TYPES_COUNT; i++) {
```
Comment (jpfr) [inline src/ua_types_encoding_binary.c]: I don't get why you loop over the types and then call findDataType.
That's a bit redundant imho.

I see three loops going over the types. Imho we should only use findDataTypes in each of these places.

File: include/ua_types.h [hunk 2]
```diff
@@ -745,6 +745,8 @@ struct UA_DataType {
                                     pointers */
     UA_Boolean overlayable  : 1; /* The type has the identical memory layout in
                                     memory and on the binary stream. */
+    UA_UInt32  xmlEncodingId;    /* NodeId of datatype when encoded as XML */
+    UA_UInt32  binaryEncodingId;    /* NodeId of datatype when encoded as XML */
```
Comment (jpfr) [inline include/ua_types.h]: ... when encoded as **binary**

File: src/ua_types_encoding_binary.c (hunk 1 above)
Comment (Pro) [inline src/ua_types_encoding_binary.c]: This loop checks against `binaryEncodingId` not (as findDataType) against typeId.identifier.numeric.

But for the loop above (line 711) you are right.

I'll extract it to a separate method and avoid double-loops. But first I wanted to see if this solution would be OK in general.

Comment (jpfr) [inline src/ua_types_encoding_binary.c]: Part 6 says:
> The identifier for the DataTypeEncoding node in the Server's AddressSpace.
ExtensionObjects defined by the OPC UA specification have a numeric node
identifier assigned to them with a NamespaceIndex of 0. The numeric
identifiers are defined in A.3.

As I understand the text, we should compare for the binary encoding identifier as we do in the other two places.
Please correct me if I missunderstood.

Comment (jpfr) [inline src/ua_types_encoding_binary.c]: FindDataTypes only applies when we get a type in binary encoding.
Otherwise, we already have the pointer to the type, don't we. :smirk:

File: src/ua_types_encoding_binary.c [hunk 3]
```diff
@@ -708,13 +728,19 @@ ExtensionObject_encodeBinary(UA_ExtensionObject const *src, const UA_DataType *_
         UA_NodeId typeId = src->content.decoded.type->typeId;
         if(typeId.identifierType != UA_NODEIDTYPE_NUMERIC)
             return UA_STATUSCODE_BADENCODINGERROR;
-        typeId.identifier.numeric += UA_ENCODINGOFFSET_BINARY;
+        const UA_DataType *type = NULL;
+        /* helping clang analyzer, typeId is numeric */
+        UA_assert(typeId.identifier.byteString.data == NULL);
+        UA_assert(typeId.identifier.string.data == NULL);
+        if (findDataType(&typeId, &type)!= UA_STATUSCODE_GOOD)
```
Comment (jpfr) [inline src/ua_types_encoding_binary.c]: We should not do a findDataType here.
We know the type. It is `src->content.decoded.type`.

Otherwise, ready to merge!

File: include/ua_types.h [hunk 4]
```diff
@@ -745,6 +745,8 @@ struct UA_DataType {
                                     pointers */
     UA_Boolean overlayable  : 1; /* The type has the identical memory layout in
                                     memory and on the binary stream. */
+    UA_UInt32  xmlEncodingId;    /* NodeId of datatype when encoded as XML */
```
Comment (jpfr) [inline include/ua_types.h]: These are 64bit * 200 types -> 1,5kb added binary size.
- Currently we don't use the xmlEncodingId. The line can be commented out.
- There is no nodeid in ns0 with an identifier > 15000.  The binaryEncodingId could become an UInt16 integer.

Comment (Pro) [inline include/ua_types.h]: I used UInt32 because UA_NodeId also uses UInt32 for the numeric representation. I'll change it here to UInt16

What about the UInt32 in UA_NodeId? Should we also change it there?

File: src/ua_types_encoding_binary.c (hunk 3 above)
Comment (Pro) [inline src/ua_types_encoding_binary.c]: Yes, correct. So we don't need the `findDataType` at all.

**Comment by Pro** [comment]
@jpfr done. Ready to merge.

**Comment by jpfr** [comment]
Looks great! Merged.
