### PR TITLE
[REVIEW] fix(el): win32 shutdown takes 120 s

### LINKED ISSUE #4964: Win32 Shutdown takes 120s when (unresponsive?) clients connected
## Description
When `running` is set to false, `UA_Server_run` takes ~120s to return, when a Client is still connected.

## Background Information / Reproduction Steps
The error was discovered here, after upgrading this test to the new open62541-Version with the event-loop:
https://github.com/umati/Sample-Server/blob/690cb0e590eeaaf3ee4c1e085995944b1b785fb4/tests/Test_BindWrongDatatype.cpp

- Start Server
- Connect Client
- Do some work
- Do not disconnect the client, do not call run_iterate (do not use the client anymore)
- Set running of `UA_Server_run` to false
- Wait ~120s until the Server is shut down

## Debugging

https://github.com/open62541/open62541/blob/5f5214427b62e96e066270f4c2798f68b1375213/arch/eventloop_posix_tcp.c#L814-L819
- The listening-Sockets are closed fast, as `TCP_close` is used 
- The client connections take the `TCP_shutdownConnection` path.

https://github.com/open62541/open62541/blob/5f5214427b62e96e066270f4c2798f68b1375213/arch/eventloop_posix_tcp.c#L503

- `UA_shutdown((UA_FD)connectionId, SD_BOTH)` (win32 `shutdown` - function is used)

(120s) gap

https://github.com/open62541/open62541/blob/5f5214427b62e96e066270f4c2798f68b1375213/arch/eventloop_posix_select.c#L162

 -  A new receive-event is issued and as there is an error, the connection is finally closed

https://github.com/open62541/open62541/blob/5f5214427b62e96e066270f4c2798f68b1375213/arch/eventloop_posix_tcp.c#L503

According to https://docs.microsoft.com/en-us/windows/win32/api/winsock/nf-winsock-shutdown the shutdown function is not used as expected in the library. As `SD_BOTH` is passed to  `shutdown`, any subsequent call to `recv` is disallowed (-1 is returned).

The proposed sequence is instead (taken from the [doc](https://docs.microsoft.com/en-us/windows/win32/api/winsock/nf-winsock-shutdown)):

1. Call shutdown with how=SD_SEND.
2. Call [recv](https://docs.microsoft.com/en-us/windows/desktop/api/winsock/nf-winsock-recv) or [WSARecv](https://docs.microsoft.com/en-us/windows/desktop/api/winsock2/nf-winsock2-wsarecv) until the function completes with success and indicates zero bytes were received. If SOCKET_ERROR is returned, then the graceful disconnect is not possible.
3. Call [closesocket](https://docs.microsoft.com/en-us/windows/desktop/api/winsock/nf-winsock-closesocket).

## Possible solutions

- Keep using `SD_BOTH` and directly call closesocket afterwards.
- Use the flow from the docs. (I don't know how to issue an event when there is no data to receive)

Full output, the 120s Gap can be seen at the end (DNS-Names are [HIDDEN]).
```
[2022-02-18 09:09:39.896 (UTC+0100)] warn/userland      AcceptAll Certificate Verification. Any remote certificate will be accepted.
[2022-02-18 09:09:40.076 (UTC+0100)] warn/server        AccessControl: Unconfigured AccessControl. Users have all permissions.
[2022-02-18 09:09:40.076 (UTC+0100)] info/server        AccessControl: Anonymous login is enabled
[2022-02-18 09:09:40.077 (UTC+0100)] info/server        AccessControl: x509 certificate user authentication is enabled
[2022-02-18 09:09:40.077 (UTC+0100)] warn/server        Username/Password Authentication configured, but no encrypting SecurityPolicy. This can leak credentials on the network.
[2022-02-18 09:09:40.077 (UTC+0100)] warn/userland      AcceptAll Certificate Verification. Any remote certificate will be accepted.
[2022-02-18 09:09:40.077 (UTC+0100)] info/session       SecureChannel 0 | Session "Administrator" | AddNode (ns=2;i=1235): The value is empty. But this is only allowed for BaseDataType. Create a matching default value.
[2022-02-18 09:09:40.078 (UTC+0100)] info/eventloop     Starting the EventLoop
[2022-02-18 09:09:40.079 (UTC+0100)] info/network       TCP     | Listening on all interfaces
[2022-02-18 09:09:40.081 (UTC+0100)] info/network       TCP 304 | New server socket for "[HIDDEN]" on port 4840
[2022-02-18 09:09:40.082 (UTC+0100)] info/network       TCP 308 | New server socket for "[HIDDEN]" on port 4840
[2022-02-18 09:09:40.085 (UTC+0100)] info/network       TCP network layer listening on opc.tcp://[HIDDEN]:4840/
[2022-02-18 09:09:40.188 (UTC+0100)] info/eventloop     Starting the EventLoop
[2022-02-18 09:09:40.188 (UTC+0100)] info/network       TCP 516 | Connection opened from "[HIDDEN]" via the server socket 304
[2022-02-18 09:09:40.189 (UTC+0100)] info/channel       Connection 0 | SecureChannel 1 | SecureChannel opened with SecurityPolicy http://opcfoundation.org/UA/SecurityPolicy#None and a revised lifetime of 600.00s
[2022-02-18 09:09:40.189 (UTC+0100)] info/channel       Connection 492 | SecureChannel 1 | SecureChannel opened with SecurityPolicy http://opcfoundation.org/UA/SecurityPolicy#None and a revised lifetime of 600.00s
[2022-02-18 09:09:40.189 (UTC+0100)] info/client        Client Status: ChannelState: Open, SessionState: Closed, ConnectStatus: Good
[2022-02-18 09:09:40.190 (UTC+0100)] info/client        Selected endpoint 0 in URL opc.tcp://localhost:4840 with SecurityMode None and SecurityPolicy http://opcfoundation.org/UA/SecurityPolicy#None
[2022-02-18 09:09:40.190 (UTC+0100)] info/client        Selected UserTokenPolicy open62541-anonymous-policy with UserTokenType Anonymous and SecurityPolicy http://opcfoundation.org/UA/SecurityPolicy#None
[2022-02-18 09:09:40.190 (UTC+0100)] info/session       SecureChannel 1 | Session "" | Session created
[2022-02-18 09:09:40.190 (UTC+0100)] info/client        Client Status: ChannelState: Open, SessionState: Created, ConnectStatus: Good
[2022-02-18 09:09:40.190 (UTC+0100)] info/session       SecureChannel 1 | Session "" | ActivateSession: Session activated
[2022-02-18 09:09:40.191 (UTC+0100)] info/client        Client Status: ChannelState: Open, SessionState: Activated, ConnectStatus: Good
[2022-02-18 09:09:40.191 (UTC+0100)] warn/server        Writing the value of Node ns=2;i=58192 failed with the following reason: DataType of the value is incompatible
[2022-02-18 09:09:40.191 (UTC+0100)] info/session       SecureChannel 0 | Session "Administrator" | WriteRequest returned status code BadTypeMismatch
Writing value failed: BadTypeMismatch
[2022-02-18 09:09:40.247 (UTC+0100)] info/network       TCP     | Shutting down the ConnectionManager
[2022-02-18 09:09:40.247 (UTC+0100)] info/network       TCP 308 | Socket closed
[2022-02-18 09:09:40.248 (UTC+0100)] info/network       TCP 304 | Socket closed
[2022-02-18 09:11:40.257 (UTC+0100)] info/server        closing connection
[2022-02-18 09:11:40.257 (UTC+0100)] info/network       TCP 516 | Socket closed
[2022-02-18 09:11:40.258 (UTC+0100)] info/network       TCP     | Shutting down the ConnectionManager
[2022-02-18 09:11:40.259 (UTC+0100)] info/eventloop     Stopping the EventLoop
[2022-02-18 09:11:40.259 (UTC+0100)] info/eventloop     The EventLoop has stopped
```
PS: The `WriteRequest returned status code BadTypeMismatch` is intentional in this test (as is has crashed my app in the past, so it's tested now.)

## Checklist

Please provide the following information:

 - [x] open62541 Version (release number or git tag): 5f5214427b62e96e066270f4c2798f68b1375213
 - [x] Other OPC UA SDKs used (client or server): open62541
 - [x] Operating system: Win 10
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [x] Self-contained code example attached
 - [ ] Critical issue

### PR DESCRIPTION
**Pull request by JanSurft**
resolves #4964 

This fix resolves 120 sek timeout for win32 shutdown of tcp connections.

### HOW:

1. calls shutdown "SD_SEND" for connections to be shut down
2. adds a delayed callback that closes a tcp connection after a peek to recv showed no data on the socket
3. if there is peeked data on the socket the delayed callback adds itself again and waits another cycle of the eventloop to process the data that arrived on the socket

### WHY:

As mentioned in the according issue by @ccvca, according to win32 documentation this is the correct way of shutting down a socket gracefully:

> 1. Call shutdown with how=SD_SEND.
> 2. Call [recv](https://docs.microsoft.com/en-us/windows/desktop/api/winsock/nf-winsock-recv) or [WSARecv](https://docs.microsoft.com/en-us/windows/desktop/api/winsock2/nf-winsock2-wsarecv) until the function completes with success and indicates zero bytes were received. If SOCKET_ERROR is returned, then the graceful disconnect is not possible.
> 3. Call [closesocket](https://docs.microsoft.com/en-us/windows/desktop/api/winsock/nf-winsock-closesocket).

https://docs.microsoft.com/en-us/windows/win32/api/winsock/nf-winsock-shutdown#remarks

### TODO:

- [x] Check if VScode CI executes unit tests
- [x] write test(s) for code coverage pass

### CODE REVIEW

**Comment by GoetzGoerisch** [comment]
Thanks @JanSurft!
Working on our end: https://github.com/umati/Sample-Server/actions/runs/1979790663

File: arch/eventloop_posix_tcp.c [hunk 1]
```diff
@@ -490,6 +490,66 @@ TCP_registerListenSocketDomainName(UA_ConnectionManager *cm, const char *hostnam
     return UA_STATUSCODE_GOOD;
 }
 
+#ifdef _WIN32
+static
+UA_RegisteredFD *
```
Comment (jpfr) [inline arch/eventloop_posix_tcp.c:495]: In all the other functions, we say
```c
static UA_RegisteredFD *
findRegisteredFD(TCPConnectionManager *cm, uintptr_t connectionId) {
```

Please keep with the established code formatting.

File: arch/eventloop_posix_tcp.c [hunk 2]
```diff
@@ -490,6 +490,66 @@ TCP_registerListenSocketDomainName(UA_ConnectionManager *cm, const char *hostnam
...
+findRegisteredFD(TCPConnectionManager *cm, uintptr_t connectionId) {
+    UA_RegisteredFD *rfd, *rfd_tmp;
+    LIST_FOREACH_SAFE(rfd, &cm->fds, es_pointers, rfd_tmp) {
+
+        if (rfd->fd == connectionId) {
```
Comment (jpfr) [inline arch/eventloop_posix_tcp.c:500]: No space after `if`.
For simple single-line `if`, leave out the brackets.

File: arch/eventloop_posix_tcp.c [hunk 3]
```diff
@@ -490,6 +490,66 @@ TCP_registerListenSocketDomainName(UA_ConnectionManager *cm, const char *hostnam
...
+    int ret = UA_recv(rfd->fd, (char *)response.data, response.length, MSG_DONTWAIT | MSG_PEEK);
+    if(ret == 0 || ret == -1) {
+        cm->connectionCallback(cm, (uintptr_t)rfd->fd, &rfd->context,
+                               UA_STATUSCODE_BADCONNECTIONCLOSED,
+                               0, NULL, UA_BYTESTRING_NULL);
+        TCP_close(tcm, rfd);
+    } else {
+
+        /* add the delayed shutdown callback again because the peeked data will be processed in the next el cycle */
+        UA_DelayedCallback *explicitlyDelayedShutdownCallback = createExplicitlyDelayedShutdownCallback(cm, rfd, delayedShutdownCallback);
```
Comment (jpfr) [inline arch/eventloop_posix_tcp.c:536]: Move logging and `addDelayedCallback` into `createExplicitlyDelayedShutdownCallback`.
Currently you have duplicate code after both usage points of `createExplicitlyDelayedShutdownCallback`.
At this time, you don't need the callback argument.
Because you use the same callback in both cases.

File: arch/eventloop_posix_tcp.c [hunk 4]
```diff
@@ -490,6 +490,66 @@ TCP_registerListenSocketDomainName(UA_ConnectionManager *cm, const char *hostnam
...
+        if (explicitlyDelayedShutdownCallback == NULL) {
+            UA_LOG_SOCKET_ERRNO_WRAP(
+                UA_LOG_ERROR(cm->eventSource.eventLoop->logger,
```
Comment (jpfr) [inline arch/eventloop_posix_tcp.c:539]: This is rather a warning.
Because we just get some additional delay (120s).
But there is no major disruption.

Also add a comment that if `createExplicitlyDelayedShutdownCallback` fails, the connection will still be closed eventually.

File: arch/eventloop_posix_tcp.c [hunk 5]
```diff
@@ -490,6 +490,66 @@ TCP_registerListenSocketDomainName(UA_ConnectionManager *cm, const char *hostnam
...
+    TCPConnectionManager *tcm = (TCPConnectionManager*)cm;
+    UA_RegisteredFD* rfd = (UA_RegisteredFD *) data;
+
+    UA_ByteString response = tcm->rxBuffer;
+    int ret = UA_recv(rfd->fd, (char *)response.data, response.length, MSG_DONTWAIT | MSG_PEEK);
+    if(ret == 0 || ret == -1) {
+        cm->connectionCallback(cm, (uintptr_t)rfd->fd, &rfd->context,
+                               UA_STATUSCODE_BADCONNECTIONCLOSED,
+                               0, NULL, UA_BYTESTRING_NULL);
+        TCP_close(tcm, rfd);
```
Comment (jpfr) [inline arch/eventloop_posix_tcp.c:532]: You can early-return here.
So you don't need the else-case.

File: arch/eventloop_posix_tcp.c [hunk 6]
```diff
@@ -490,6 +490,66 @@ TCP_registerListenSocketDomainName(UA_ConnectionManager *cm, const char *hostnam
...
+                UA_LOG_ERROR(cm->eventSource.eventLoop->logger,
+                             UA_LOGCATEGORY_NETWORK,
+                             "TCP %u\t| Error Out of memory for creating delayed shutdown callback (%s)",
+                             (unsigned)rfd->fd, errno_str));
+            return;
+        }
+
+        UA_EventLoop *el = cm->eventSource.eventLoop;
+        el->addDelayedCallback(el, explicitlyDelayedShutdownCallback);
+        return;
```
Comment (jpfr) [inline arch/eventloop_posix_tcp.c:548]: No return required here.

**Review by jpfr — COMMENTED** [review]
Looks good!
Just one CI error on Windows
`54 : ~~Dr.M~~ error #1: UNADDRESSABLE ACCESS of freed memory: reading 0x01dc5e90-0x01dc5e94 4 byte(s) [D:\a\1\s\build\tests\test-verbose.vcxproj]`
and a few cosmetic comments.

File: arch/eventloop_posix_tcp.c [hunk 7]
```diff
@@ -490,6 +490,66 @@ TCP_registerListenSocketDomainName(UA_ConnectionManager *cm, const char *hostnam
...
 
+#ifdef _WIN32
+static
+UA_RegisteredFD *
+findRegisteredFD(TCPConnectionManager *cm, uintptr_t connectionId) {
+    UA_RegisteredFD *rfd, *rfd_tmp;
+    LIST_FOREACH_SAFE(rfd, &cm->fds, es_pointers, rfd_tmp) {
+
+        if (rfd->fd == connectionId) {
+            return rfd;
```
[the remark this answers is not in the document]
Comment (JanSurft) [reply arch/eventloop_posix_tcp.c:499]: I would say "explicit is better than implicit". Because it is opaque to the reader of the code that `LIST_FOREACH` assigns to `rfd` in every loop iteration. And that this assignment is still valid after exiting the loop.

Leaving it like this, it is more clear in my opinion, it also saves no lines of code.

File: arch/eventloop_posix_tcp.c (hunk 3 above)
Comment (JanSurft) [reply arch/eventloop_posix_tcp.c:544]: It was meant to be like this.  In `delayedShutdownCallback` the logging needs to be inline because I cannot return an error-code. Whereas in the other place I can return `UA_STATUSCODE_BADOUTOFMEMORY` and propagate the error and handle logging somewhere else.

As for the two lines of code that get the eventloop and add the callback, I would again say "explicit is better than implicit". The callback is created via `create...` and then added to the eventloop. If possible I like functions that serve as little purposes as possible.

File: arch/eventloop_posix_tcp.c (hunk 5 above)
Comment (JanSurft) [reply arch/eventloop_posix_tcp.c:541]: I would prefer the if/else way because it carries the semantic of what is to be done there:

"if we receive nothing or if there is a receive-error, then close the socket. Else recreate the delayed shutdown callback and add it to the loop again."

File: arch/eventloop_posix_tcp.c (hunk 2 above)
Comment (jpfr) [reply arch/eventloop_posix_tcp.c:498]: Still todo.
Ideally set your editor to not do this automatically.

File: arch/eventloop_posix_tcp.c (hunk 3 above)
Comment (jpfr) [reply arch/eventloop_posix_tcp.c:541]: The calling function cannot handle an out-of-memory any better.
So we should handle it internally and not propagate the error outside of the current scope.

Normally we would reserve the memory already when the connection is created, so that the cleanup always works.
This pattern is also used in other places in the SDK already.

However, here the worst that can happen is a 120 second wait for the server shutdown.
And only on win32 where we are typically not memory constrained.
Hence, log the error with a warning and do not return an error code.

And with this, the two code paths can be merged as in the original review comment.

File: arch/eventloop_posix_tcp.c [hunk 8]
```diff
@@ -490,6 +490,70 @@ TCP_registerListenSocketDomainName(UA_ConnectionManager *cm, const char *hostnam
...
+
+static UA_DelayedCallback
+*createExplicitlyDelayedShutdownCallback(UA_ConnectionManager *cm, UA_RegisteredFD *rfd, UA_Callback callback) {
+    UA_DelayedCallback *explicitlyDelayedShutdownCallback = (UA_DelayedCallback*) UA_malloc(sizeof(UA_DelayedCallback));
+    if (!explicitlyDelayedShutdownCallback) {
+        return NULL;
+    }
+    explicitlyDelayedShutdownCallback->callback = callback;
+    explicitlyDelayedShutdownCallback->application = cm;
+    UA_FD *fd = (UA_FD *) UA_malloc(sizeof(UA_FD));
```
Comment (jpfr) [inline arch/eventloop_posix_tcp.c:513]: The FD always fits into the size of a pointer.
So you don't have to allocate this memory here.
Just cast the pointer itself.

File: arch/eventloop_posix_tcp.c (hunk 5 above)
Comment (jpfr) [reply arch/eventloop_posix_tcp.c:538]: An early return has the same semantics.
With the pointer-trick mentioned in another comment you get rid of the final `UA_free(data)`.

Ideally, the "happy case" of the control flow is linear and does not flow through nested blocks with `{ }` braces.
That can be achieved by branching out the edge cases with an early return.

As often, it is a question of taste.
Here I would prefer an early return.

Which case is the "happy case", I let you decide. 😄

**Review by jpfr — COMMENTED** [review]
Another small improvement with this review...

**Comment by jpfr** [comment]
Nice! Squash-merged.
