### PR TITLE
be more compliant fix #1362 (fix NS Compiler for opaque type)

### LINKED ISSUE #1362: Siemens OPC Scout V10 problem
Description
===========

Problem when trying to monitor items with OPC Scout V10 client with open62541 server (bin/examples/server)

If I try to monitor "current time" item : 

image

OPC Scout V10 shows : 

For subscriptions : 
Type : null
Result : Bad_WaitingForInitialData
and it does not show any value

On the right ("Properties" tab), all seem to be correct. 

PublishResponse seem to be valid : 

scoot2

If I click on read, the value are displayed : 

scoot3

If I try to write a value with OPC Scout, I have : 

image

Can we have a problem with Data type in PublishResponse ?  Like  https://github.com/open62541/open62541/issues/1317 ?

Has anyone ever tried open62541 server with OPC Scout V10 client?

Checklist
=========
Please provide the following information:

 - [X] open62541 Version master
 - [X] Other OPC UA SDKs used (client or server):

### PR DESCRIPTION
**Pull request by StalderT**
OPCScout need to have valueRank=-1 for Scalar node. To be compatible (if we want to be) we need to change valueRank for ns0 node.

image

Ok for the two variables changed in this PR. Not Ok for current time in ns0 (Type null). 

Works fine if I manually edit generated code from : 
```
/* CurrentTime - ns=0;i=2258 */
{
UA_VariableAttributes attr = UA_VariableAttributes_default;
attr.minimumSamplingInterval = 0.000000;
attr.userAccessLevel = 1;
attr.accessLevel = 1;
attr.valueRank = -2; 
attr.dataType = UA_NODEID_NUMERIC(ns0,13);
void *variablenode_ns_0_i_2258_variant_DataContents = UA_alloca(UA_TYPES[UA_TYPES_DATETIME].memSize);
UA_init(variablenode_ns_0_i_2258_variant_DataContents, &UA_TYPES[UA_TYPES_DATETIME]);
UA_Variant_setScalar(&attr.value, variablenode_ns_0_i_2258_variant_DataContents, &UA_TYPES[UA_TYPES_DATETIME]);
attr.displayName = UA_LOCALIZEDTEXT("", "CurrentTime");
attr.description = UA_LOCALIZEDTEXT("", "");
attr.writeMask = 0;
attr.userWriteMask = 0;
retVal |= UA_Server_addVariableNode(server,
UA_NODEID_NUMERIC(ns0,2258),
UA_NODEID_NUMERIC(ns0,0),
UA_NODEID_NUMERIC(ns0,0),
UA_QUALIFIEDNAME(ns0, "CurrentTime"),
UA_NODEID_NUMERIC(ns0,63),
attr,
NULL, NULL);
}

retVal |= UA_Server_addReference(server, UA_NODEID_NUMERIC(ns0,2258), UA_NODEID_NUMERIC(ns0,47), UA_EXPANDEDNODEID_NUMERIC(ns0, 2256), false);

```

to

```
/* CurrentTime - ns=0;i=2258 */
{
UA_VariableAttributes attr = UA_VariableAttributes_default;
attr.minimumSamplingInterval = 0.000000;
attr.userAccessLevel = 1;
attr.accessLevel = 1;
attr.valueRank = -1;
attr.dataType = UA_NODEID_NUMERIC(ns0,13);
void *variablenode_ns_0_i_2258_variant_DataContents = UA_alloca(UA_TYPES[UA_TYPES_DATETIME].memSize);
UA_init(variablenode_ns_0_i_2258_variant_DataContents, &UA_TYPES[UA_TYPES_DATETIME]);
UA_Variant_setScalar(&attr.value, variablenode_ns_0_i_2258_variant_DataContents, &UA_TYPES[UA_TYPES_DATETIME]);
attr.displayName = UA_LOCALIZEDTEXT("", "CurrentTime");
attr.description = UA_LOCALIZEDTEXT("", "");
attr.writeMask = 0;
attr.userWriteMask = 0;
retVal |= UA_Server_addVariableNode(server,
UA_NODEID_NUMERIC(ns0,2258),
UA_NODEID_NUMERIC(ns0,0),
UA_NODEID_NUMERIC(ns0,0),
UA_QUALIFIEDNAME(ns0, "CurrentTime"),
UA_NODEID_NUMERIC(ns0,63),
attr,
NULL, NULL);
}

retVal |= UA_Server_addReference(server, UA_NODEID_NUMERIC(ns0,2258), UA_NODEID_NUMERIC(ns0,47), UA_EXPANDEDNODEID_NUMERIC(ns0, 2256), false);

```

I have try to change here (to -1) : 
https://github.com/open62541/open62541/blob/3db5c9bde1c22d7d9de3c2284a89401f6978d084/tools/nodeset_compiler/nodes.py#L230

But it was not a good idea :-)

```
[11/28/2017 13:44:55.418] info/session	Connection 0 | SecureChannel 0 | Session 00000001-0000-0000-0000-000000000000 | AddNodes: Type-checking the variable node failed with error code BadTypeMismatch
[11/28/2017 13:44:55.419] info/session	Connection 0 | SecureChannel 0 | Session 00000001-0000-0000-0000-000000000000 | AddNodes: Type-checking the variable node failed with error code BadTypeMismatch
[11/28/2017 13:44:55.419] info/session	Connection 0 | SecureChannel 0 | Session 00000001-0000-0000-0000-000000000000 | AddNodes: Type-checking the variable node failed with error code BadTypeMismatch
[11/28/2017 13:44:55.420] info/session	Connection 0 | SecureChannel 0 | Session 00000001-0000-0000-0000-000000000000 | AddNodes: Type-checking the variable node failed with error code BadTypeMismatch
[11/28/2017 13:44:55.421] info/session	Connection 0 | SecureChannel 0 | Session 00000001-0000-0000-0000-000000000000 | AddNodes: Type-checking the variable node failed with error code BadTypeMismatch
[11/28/2017 13:44:55.421] info/session	Connection 0 | SecureChannel 0 | Session 00000001-0000-0000-0000-000000000000 | AddNodes: Type-checking the variable node failed with error code BadTypeMismatch
[11/28/2017 13:44:55.423] info/session	Connection 0 | SecureChannel 0 | Session 00000001-0000-0000-0000-000000000000 | AddNodes: Type-checking the variable node failed with error code BadTypeMismatch
[11/28/2017 13:44:55.423] info/session	Connection 0 | SecureChannel 0 | Session 00000001-0000-0000-0000-000000000000 | AddNodes: Type-checking the variable node failed with error code BadTypeMismatch
[11/28/2017 13:44:55.425] error/server	Initialization of Namespace 0 failed with BadTypeMismatch. See previous outputs for any error messages.
Segmentation fault
```

I know that -2 is comptabile with specification, but would you like to change this? If yes, can someone make this?

### CODE REVIEW

File: src/server/ua_server_ns0.c [hunk 1]
```diff
@@ -558,7 +558,7 @@ UA_Server_initNS0(UA_Server *server) {
     /* LocaleIdArray */
     UA_LocaleId locale_en = UA_STRING("en");
     retVal |= writeNs0VariableArray(server, UA_NS0ID_SERVER_SERVERCAPABILITIES_LOCALEIDARRAY,
-                                    &locale_en, 1, &UA_TYPES[UA_TYPES_LOCALEID]);
+                                    &locale_en, 1, &UA_TYPES[UA_TYPES_STRING]);
```
Comment (Pro) [inline src/server/ua_server_ns0.c]: Shouldn't it still be LOCALEID?
If that's not correctly shown on the client side (e.g. it only shows ExtensionObject) then we maybe have a problem in encoding which we should try to fix?

**Comment by StalderT** [comment]
When a problem occure, opcua.demo-this.com send a serviceFault response : 

image

open62541 send a requestResponse with the a bad service result : 

image

Can you confirm that it is correct and that open62541 don't need to send a serviceFault message?

File: src/server/ua_server_ns0.c (hunk 1 above)
Comment (StalderT) [reply src/server/ua_server_ns0.c]: in the generated code, it is defined as a UA_TYPE_STRING :

```
/* LocaleIdArray - ns=0;i=2271 */
{
UA_VariableAttributes attr = UA_VariableAttributes_default;
attr.minimumSamplingInterval = 0.000000;
attr.userAccessLevel = 1;
attr.accessLevel = 1;
attr.valueRank = 1;
attr.arrayDimensionsSize = 1;
attr.arrayDimensions = (UA_UInt32 *)UA_Array_new(1, &UA_TYPES[UA_TYPES_UINT32]);
attr.arrayDimensions[0] = 0;
attr.dataType = UA_NODEID_NUMERIC(ns0,12);
UA_String *variablenode_ns_0_i_2271_variant_DataContents = (UA_String*) UA_alloca(UA_TYPES[UA_TYPES_STRING].memSize * 1); 
UA_init(&variablenode_ns_0_i_2271_variant_DataContents[0], &UA_TYPES[UA_TYPES_STRING]);
UA_Variant_setArray( &attr.value, variablenode_ns_0_i_2271_variant_DataContents, (UA_Int32) 1, &UA_TYPES[UA_TYPES_STRING]);
attr.displayName = UA_LOCALIZEDTEXT("", "LocaleIdArray");
attr.description = UA_LOCALIZEDTEXT("", "A list of locales supported by the server.");
attr.writeMask = 0;
attr.userWriteMask = 0;
retVal |= UA_Server_addVariableNode(server,
UA_NODEID_NUMERIC(ns0,2271),
UA_NODEID_NUMERIC(ns0,0),
UA_NODEID_NUMERIC(ns0,0),
UA_QUALIFIEDNAME(ns0, "LocaleIdArray"),
UA_NODEID_NUMERIC(ns0,68),
attr,
NULL, NULL);
UA_Array_delete(attr.arrayDimensions, 1, &UA_TYPES[UA_TYPES_UINT32]);
}

retVal |= UA_Server_addReference(server, UA_NODEID_NUMERIC(ns0,2271), UA_NODEID_NUMERIC(ns0,46), UA_EXPANDEDNODEID_NUMERIC(ns0, 2268), false);
```

Comment (Pro) [reply src/server/ua_server_ns0.c]: According to the spec the LocaleIdArray should be of type `LocaleId[]` and not `String[]`

Comment (StalderT) [reply src/server/ua_server_ns0.c]: Ok thanks.

Comment (StalderT) [reply src/server/ua_server_ns0.c]: Do you have any news about this issue?

Comment (StalderT) [reply src/server/ua_server_ns0.c]: In this case we have the same problem for all opaque type. Eg: CurrentTime sould be of type UtcTime but is currently as type DateTime.

image

and readCurrentTime use UA_TYPES_DATETIME instead of UtcTime

```
static UA_StatusCode
readCurrentTime(UA_Server *server, const UA_NodeId *sessionId, void *sessionContext,
                const UA_NodeId *nodeid, void *nodeContext, UA_Boolean sourceTimeStamp,
                const UA_NumericRange *range, UA_DataValue *value) {
    if(range) {
        value->hasStatus = true;
        value->status = UA_STATUSCODE_BADINDEXRANGEINVALID;
        return UA_STATUSCODE_GOOD;
    }
    UA_DateTime currentTime = UA_DateTime_now();
    UA_StatusCode retval = UA_Variant_setScalarCopy(&value->value, &currentTime,
                                                    &UA_TYPES[UA_TYPES_DATETIME]);
    if(retval != UA_STATUSCODE_GOOD)
        return retval;
    value->hasValue = true;
    if(sourceTimeStamp) {
        value->hasSourceTimestamp = true;
        value->sourceTimestamp = currentTime;
    }
    return UA_STATUSCODE_GOOD;
}
```

If I try to modify readCurrentTime (using UA_TYPES_UTCTIME) 
```
static UA_StatusCode
readCurrentTime(UA_Server *server, const UA_NodeId *sessionId, void *sessionContext,
                const UA_NodeId *nodeid, void *nodeContext, UA_Boolean sourceTimeStamp,
                const UA_NumericRange *range, UA_DataValue *value) {
    if(range) {
        value->hasStatus = true;
        value->status = UA_STATUSCODE_BADINDEXRANGEINVALID;
        return UA_STATUSCODE_GOOD;
    }
    UA_DateTime currentTime = UA_DateTime_now();
    UA_StatusCode retval = UA_Variant_setScalarCopy(&value->value, &currentTime,
                                                    &UA_TYPES[UA_TYPES_UTCTIME]);
    if(retval != UA_STATUSCODE_GOOD)
        return retval;
    value->hasValue = true;
    if(sourceTimeStamp) {
        value->hasSourceTimestamp = true;
        value->sourceTimestamp = currentTime;
    }
    return UA_STATUSCODE_GOOD;
}
```
UaExpert display extensionobjet for the value (like LocaleIdArray)

image

**Comment by StalderT** [comment]
Latest commit fix the NS Compiler for opaque dataType and use valueRanks -1 for scalar VariableNode. For me ready to merge.

image

image

**Comment by StalderT** [comment]
fix https://github.com/open62541/open62541/issues/1362

**Comment by StalderT** [comment]
Do you have any comments or questions about this PR?

File: tools/generate_datatypes.py [hunk 2]
```diff
@@ -465,8 +465,23 @@ def iter_types(v):
         l = list(filter(lambda t: t.name in selected_types, l))
     if args.no_builtin:
         l = list(filter(lambda t: type(t) != BuiltinType, l))
+    # remove opaque type
+    l = list(filter(lambda t: t.name not in opaque_type_mapping, l))
     return l
 
+def iter_opaque_types(v):
```
Comment (Pro) [inline tools/generate_datatypes.py]: Since `iter_opaque_types` is nearly the same as `iter_types` you can remove `iter_opaque_types` and instead pass a parameter to `iter_types`.

e.g. `def iter_types(v, includeOpaque):` and use it in the filter correspondingly

**Comment by Pro** [comment]
@StalderT can you change what I mentioned in the comment and rebase on master?

Then we can merge this. Thanks!

File: tools/generate_datatypes.py (hunk 2 above)
Comment (StalderT) [reply tools/generate_datatypes.py]: Changes done!
